# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provision :ansible do |ansible|
    ansible.playbook = '../ops/ansible/fancy-playbook.yaml'
    ansible.groups = {
      "app" => ["app-1", "app-2", "app-3"],
      "db"  => ["db-1", "db-2"],
      "web" => ["web"]
    }
  end
#  config.vm.network "private_network", type: "dhcp"

  config.vm.define "web" do |app|
    app.vm.network "private_network", ip: "172.20.10.10"
    app.vm.hostname = "web"
  end

  (1..3).each do |n|
    config.vm.define "app-#{n}", autostart: n == 1 do |app|
      app.vm.synced_folder "../app", "/app", mode: '777'
      app.vm.network "private_network", ip: "172.20.10.2#{n}"
      app.vm.hostname = "app-#{n}"
    end
  end

  (1..2).each do |n|
    config.vm.define "db-#{n}", autostart: n == 1  do |db|
      db.vm.network "private_network", ip: "172.20.10.3#{n}"
      db.vm.hostname = "db-#{n}"
    end
  end
end
